# Site Settings
title: Gareth Beddis - Software Engineer
description: >
  22 year old studying Software Engineering at Cardiff university.
skills: >
  Experienced in lorem ipsum dolor sit amet, consectetur adipiscing elit.
  Curabitur sodales cursus laoreet. Vivamus at mauris eu neque venenatis vestibulum et eu est.
author: Gareth Beddis
email: garethbeddis@gmail.com
social_profile: GarethBeddis
avatar: assets/images/avatar.jpg
baseurl: ""
url: "http://garethbeddis.github.io"
